name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        yarn install --cache-folder .yarn-cache
        cd demo && yarn install --cache-folder ../.yarn-cache
    - name: build
      run: yarn build
    - name: test
      run: yarn test
      env:
        CI: true
    - name: test coverage
      if: github.ref == 'refs/heads/master' && matrix.node-version == '14.x'
      run: yarn test:coverage
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_DOCS: ${{ secrets.BASE_DOCS }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        CODECOVS_TOKEN: ${{ secrets.CODECOVS_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Release
      if: github.ref == 'refs/heads/master' && matrix.node-version == '14.x'
      run: yarn semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#    - name: release
#      if: github.ref == 'refs/heads/master' && matrix.node-version == '14.x'
#      uses: cycjimmy/semantic-release-action@v2.5.0
#      env:
#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
#        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
